version: '3.1'
services:
  cassandra-seed-dc1-rack1-node1:
    image: cassandra:4.0
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc1-rack1-node1
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
  cassandra-seed-dc2-rack1-node1:
    image: cassandra:4.0
    ports:
      - "9043:9042"
      - "7001:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc2-rack1-node1
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql

  cassandra-node-dc1-rack1-node2:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc1-rack1-node2
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties

  cassandra-node-dc2-rack1-node2:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc2-rack1-node2
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
  
  cassandra-node-dc1-rack1-node3:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc1-rack1-node3
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
  
  cassandra-node-dc2-rack1-node3:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Dcassandra.jmx.local.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=cassandra-seed-dc2-rack1-node3
    networks:
      - cassandra-reaper
    volumes:
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
  
  cassandra-reaper:
    image: thelastpickle/cassandra-reaper:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - REAPER_JMX_AUTH_USERNAME=cassandra
      - REAPER_JMX_AUTH_PASSWORD=cassandra
      - REAPER_STORAGE_TYPE=cassandra
      - REAPER_CASS_CLUSTER_NAME=cassandra-cluster
      - REAPER_CASS_CONTACT_POINTS=["172.22.0.5","172.22.0.2"]
      - REAPER_CASS_KEYSPACE=reaper_db
      - REAPER_CASS_AUTH_ENABLED=false
    depends_on:
      - cassandra-seed-dc1-rack1-node1
      - cassandra-seed-dc2-rack1-node1
    networks:
      - cassandra-reaper

networks:
  cassandra-reaper:
    driver: bridge