version: '3.1'
services:
  cassandra-seed-dc1-rack1-node1:
    image: cassandra:4.1.1
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
      - cassandra-seed-dc1-rack1-node1-data:/var/lib/cassandra
  cassandra-seed-dc2-rack1-node1:
    image: cassandra:4.1.1
    ports:
      - "9043:9042"
      - "7001:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
      - cassandra-seed-dc2-rack1-node1-data:/var/lib/cassandra
  cassandra-node-dc1-rack1-node2:
    image: cassandra:4.1.1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - cassandra-node-dc1-rack1-node2-data:/var/lib/cassandra
  cassandra-node-dc2-rack1-node2:
    image: cassandra:4.1.1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - cassandra-node-dc2-rack1-node2-data:/var/lib/cassandra
  cassandra-seed-dc3-rack1-node1:
    image: cassandra:4.1.1
    ports:
      - "9044:9042"
      - "7002:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc3
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc3-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
      - cassandra-seed-dc3-rack1-node1-data:/var/lib/cassandra
  cassandra-node-dc3-rack1-node2:
    image: cassandra:4.1.1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc3
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-seed-dc3-rack1-node1
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    networks:
      - cassandra
    volumes:
      - ./cassandra-rackdc-dc3-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - cassandra-node-dc3-rack1-node2-data:/var/lib/cassandra

networks:
  cassandra:
    driver: bridge

volumes:
  cassandra-seed-dc1-rack1-node1-data:
  cassandra-seed-dc2-rack1-node1-data:
  cassandra-node-dc1-rack1-node2-data:
  cassandra-node-dc2-rack1-node2-data:
  cassandra-seed-dc3-rack1-node1-data:
  cassandra-node-dc3-rack1-node2-data:

